// app/layout.tsx
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"], // pick the weights you need
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // return (
  //   <html lang="en">
  //     <body className={`${openSans.variable} antialiased`}>
  //       {children}
  //     </body>
  //   </html>
  // );
  // inside your RootLayout return, add a <head> sibling to <body>
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          name="format-detection"
          content="telephone=no,email=no,address=no"
        />
      </head>
      <body className={`${openSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
